config/routes.rb
Multiplefileuplad::Application.routes.draw do
  root :to => redirect("/uploads/new")

  match 'uploads/new' => 'uploads#new_get' , :via => [:get]
  match 'uploads/new' => 'uploads#new_post', :via => [:post]

end

app/models/upload.rb
class Upload
  #  include ActiveModel::Model ##Rails 4
  extend  ActiveModel::Naming
  extend  ActiveModel::Translation
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :files

  def initialize(params={})
    params.each do |attr, value|
      self.public_send("#{attr}=", value)
    end if params
  end
  def persisted?
    false
  end

end

app/models/user_agent.rb
class NotNilValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, "can't be nil" if value.nil?
  end
end

class UserAgent < ActiveRecord::Base
  ##http://apidock.com/rails/v3.2.8/ActiveModel/Validations/ClassMethods/validates
  attr_accessible :get_count, :last_seen, :post_multiple_count, :post_single_count, :post_zero_count, :user_agent_string

  after_initialize do
 #   self.user_agent_string ||= ""
    self.get_count ||= 0
    self.post_zero_count ||= 0
    self.post_single_count ||= 0
    self.post_multiple_count ||= 0
    self.last_seen ||= Time.zone.now.utc.iso8601
  end

  validates :user_agent_string, {
    :uniqueness => true,
    :length => { :in => 0..255 },
    :not_nil => true
  }
  validates :last_seen, {
    :presence => true,
    :timeliness => {:format => 'yyyy-mm-ddThh:nn:ssZ'},
    :allow_blank => false,
  }
  
  validates :get_count, :numericality => { :only_integer => true }
  validates :post_zero_count, :numericality => { :only_integer => true }
  validates :post_single_count, :numericality => { :only_integer => true }
  validates :post_multiple_count, :numericality => { :only_integer => true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads/new
  def new_get
    common

    @user_agent.increment!(:get_count)
    
    @upload = Upload.new
    respond_to do |format|
      format.html { render 'new' } # new.html.erb
    end
  end

  # POST /uploads/new
  def new_post
    common
    
    upload_params = params && params[:upload]
    @upload = Upload.new(upload_params)

    if @upload.files
      case @upload.files.count
      when 0 then @user_agent.increment!(:post_zero_count)
      when 1 then @user_agent.increment!(:post_single_count)
      else
        @user_agent.increment!(:post_multiple_count)
      end
    end

    if request.body.size < 1.megabytes
      @request_body = request.body.read
    else
      @upload.errors.add(:files, "HTTP Request body too large (> 1000 bytes)")
    end

    respond_to do |format|
      format.html { render 'new' } # new.html.erb
    end
  end

  def common
    @utf8_enforcer_tag_enabled = false
    @request_body = nil
    @user_agent = UserAgent.find_or_create_by_user_agent_string(request.env['HTTP_USER_AGENT']||"")
    @user_agent.last_seen = Time.zone.now.utc
    @user_agent.save!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multiplefileupload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
</head>
<body>
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_google_plusone" style="cursor:pointer" g:plusone:size="standard"></a>
<a class="addthis_button_preferred_1" style="cursor:pointer"></a>
<a class="addthis_button_preferred_2" style="cursor:pointer"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-504f907623f6d4d0"></script>

<%= yield %>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload, :url => { :action => "new_post" }, :multipart => true, :authenticity_token => false ) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :files %><br />
    <%= f.file_field(:files, :multiple => true) %><br/>
  </div>
  <div class="actions">
    <%= f.submit 'Submit'%>
  </div>
<% end %>

<% if @request_body -%>
<h2>The received body in the HTTP POST request:</h2>
<pre>
<%= @request_body -%>
</pre>
<% end -%>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <tr>
    <th>Files</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.files %></td>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
</article>
<h1>Multiple File Upload</h1>

<p>A small web application for investigating browser behaviour when
POSTing multiple files</p>

<p>It is a small web application that has one input field for multiple file upload, like:</p>

<pre><code>&lt;form enctype="multipart/form-data" method="post"&gt;
  &lt;input multiple="multiple" name="upload[files][]" type="file" /&gt;
&lt;/form&gt;
</code></pre>

<p>The application does not store the uploaded files anywhere, neither on disk, nor in a database. It is 100&#37; stateless.</p>

<p>The application simply spits out the the POST request body, so that you can see how different browser provide the multiple files over HTTP. If the request body exceeds 1000 bytes it will report an error.</p>

<p>The purpose of this application is to help test frameworks to mimick browser behaviour upon uploading mulitiple files in a single form <code>input</code> element with <code>type="file"</code> attribute.</p>

<p>The source code is available at <a href="http://github.com/softace/multiplefileupload">http://github.com/softace/multiplefileupload</a></p></article>

<br style="clear:both;">


<h2>New upload</h2>

<%= render 'form' %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Files:</b>
  <%= @upload.files %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>